services:
  web:
    build:
      ports:
        - "5000:5000"
        - "5678:5678"
      volumes:
        - .:/app
      command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "app.py"]
