"""empty message

Revision ID: 008522eb4381
Revises: d56d35097123
Create Date: 2025-09-25 21:39:02.310384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008522eb4381'
down_revision = 'd56d35097123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
